### ISSUE TITLE
Get a list of Contract Transactions By Address

### ISSUE THREAD

**Issue by kraikov** [aeternity/aepp-middleware#4]
# Expected Behavior

`/contracts/{address}/{startHeight}/{endHeight}/{sort}/{input}`

## Input

| Param                    | Description                                               | Type                      |
| ------------------------ |:---------------------------------------------------:|------------------------|
| address                  | Contract address.                                     | Mandatory            |
| startHeight             | Starting block height to retrieve results     | Mandatory            |
| endHeight              | Ending block height to retrieve results      | Optional                |
| sort                        | Results ordering - asc or desc                  | Optional                |
| input                      | Contract call input (which function)           | Optional                |

## Result

```
{
  "transactions": [
    {
      "tx": {
        "type": "type",
        "version": 0
      },
      "block_hash": {},
      "block_height": 6,
      "hash": ,
      "status":,
      "contractCallInput": 
      "contractCallResults":,
      "caller",
    },
    ...
  ]
}
```

**Comment by mradkov** [comment]
So, I started implementing something regarding this issue, but there are some bumps and drawbacks from the current situation of the node endpoints and the data that is being stored in the middleware's database, that complexify this a bit.

Here are the steps we need to do in order for this to work, our `fn` logic and query should be doing the following:
1. Get all the transactions for the certain contract address provided in the parameters.
2. Filter them by `start_height` and `end_height` accordingly
3. Then `iter()` over every single one of them while decoding the `call_data` field in the `t.tx` table column which happens to be a `jsonb` object - SO:
 3.1. the script should be first checking if the `call_data` exists via `jsonb_exists()`
 3.2. then get the smart contract metadata (or the so called ABI) in order for it to know how to decode the `call_data` - this is needed because every contract function call should be decoded accordingly in order for us to know which exact function calls to filter in the query.  ***IMPORTANT - Check below***
 3.3. filter the transactions according to the request's `input` parameter
4. provide the result to the endpoint
 

# ***IMPORTANT***
At this point, the mentioned decoding and getting the metadata cannot happen easily, because there is no easy API endpoint or support implemented in the node yet.

## Workaround:
- Get the serialized smart contract code from the endpoint `/contracts/{pubkey}/code`. The meta data is a part of this serialized code, so you can feed this to the compiler's endpoint and get the data nicely structured again.
- Then proceed with the decoding.

References:
Serialization - https://github.com/aeternity/protocol/blob/master/serializations.md#sophia-byte-code-version-1-roma-release
Decode endpoint - http://aeternity.com/api-docs/?config=https://raw.githubusercontent.com/aeternity/aeternity/master/apps/aehttp/priv/swagger.json#/internal/DecodeData

**Comment by kraikov** [comment]
Any progress in that? It's a huge blocker already.

**Comment by johnsnewby** [comment]
It's surprisingly complicated, and Nikita and I are hoping to sit down tomorrow and figure it out. It's on our radar, it's just difficult.

**Comment by johnsnewby** [comment]
I have a first version of this waiting to be released. Updates here when it sees the light of day.

**Comment by johnsnewby** [comment]
This was done ages ago but I neglected to close the issue
