### ISSUE TITLE
Duplicate names on testnet.mdw.aepps.com

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-middleware#92]
<details>
<summary>https://testnet.mdw.aepps.com/middleware/names/reverse/ak_2swhLkgBPeeADxVTAVCJnZLY5NZtCFiM93JxsEaMuC59euuFRQ</summary>

[{"id":83,"name":"example15.test","name_hash":"nm_2eraoUotAe6XHxkNqU8YQPgzo36UpCPyVWwKzZpA8cAN2RsqFW","tx_hash":"th_27AJYF77545XqwJSfib5HMUsUbJFzkYCNeTYbgVff8e2Mrj2Nt","created_at_height":106486,"owner":"ak_2swhLkgBPeeADxVTAVCJnZLY5NZtCFiM93JxsEaMuC59euuFRQ","expires_at":156486,"pointers":[{"id":"ak_2swhLkgBPeeADxVTAVCJnZLY5NZtCFiM93JxsEaMuC59euuFRQ","key":"account_pubkey"}]},{"id":84,"name":"example15.test","name_hash":"nm_2eraoUotAe6XHxkNqU8YQPgzo36UpCPyVWwKzZpA8cAN2RsqFW","tx_hash":"th_27AJYF77545XqwJSfib5HMUsUbJFzkYCNeTYbgVff8e2Mrj2Nt","created_at_height":106486,"owner":"ak_2swhLkgBPeeADxVTAVCJnZLY5NZtCFiM93JxsEaMuC59euuFRQ","expires_at":156486,"pointers":[{"id":"ak_2swhLkgBPeeADxVTAVCJnZLY5NZtCFiM93JxsEaMuC59euuFRQ","key":"account_pubkey"}]},{"id":85,"name":"example15.test","name_hash":"nm_2eraoUotAe6XHxkNqU8YQPgzo36UpCPyVWwKzZpA8cAN2RsqFW","tx_hash":"th_27AJYF77545XqwJSfib5HMUsUbJFzkYCNeTYbgVff8e2Mrj2Nt","created_at_height":106486,"owner":"ak_2swhLkgBPeeADxVTAVCJnZLY5NZtCFiM93JxsEaMuC59euuFRQ","expires_at":156486,"pointers":[{"id":"ak_2swhLkgBPeeADxVTAVCJnZLY5NZtCFiM93JxsEaMuC59euuFRQ","key":"account_pubkey"}]},{"id":86,"name":"example15.test","name_hash":"nm_2eraoUotAe6XHxkNqU8YQPgzo36UpCPyVWwKzZpA8cAN2RsqFW","tx_hash":"th_27AJYF77545XqwJSfib5HMUsUbJFzkYCNeTYbgVff8e2Mrj2Nt","created_at_height":106486,"owner":"ak_2swhLkgBPeeADxVTAVCJnZLY5NZtCFiM93JxsEaMuC59euuFRQ","expires_at":156486,"pointers":[{"id":"ak_2swhLkgBPeeADxVTAVCJnZLY5NZtCFiM93JxsEaMuC59euuFRQ","key":"account_pubkey"}]},{"id":87,"name":"example15.test","name_hash":"nm_2eraoUotAe6XHxkNqU8YQPgzo36UpCPyVWwKzZpA8cAN2RsqFW","tx_hash":"th_27AJYF77545XqwJSfib5HMUsUbJFzkYCNeTYbgVff8e2Mrj2Nt","created_at_height":106486,"owner":"ak_2swhLkgBPeeADxVTAVCJnZLY5NZtCFiM93JxsEaMuC59euuFRQ","expires_at":156486,"pointers":[{"id":"ak_2swhLkgBPeeADxVTAVCJnZLY5NZtCFiM93JxsEaMuC59euuFRQ","key":"account_pubkey"}]},{"id":6,"name":"example7.test","name_hash":"nm_22AkXCAjRjZLw2DE21PD3BAxAP9aCgrvpBuEvG5gBCaiXWyi3h","tx_hash":"th_AFYpBwzyv5bwSD1zXLnVZxegQVGyQa3nJWbH1Vvr7VNbATA3F","created_at_height":104326,"owner":"ak_2swhLkgBPeeADxVTAVCJnZLY5NZtCFiM93JxsEaMuC59euuFRQ","expires_at":154327,"pointers":[{"id":"ak_2swhLkgBPeeADxVTAVCJnZLY5NZtCFiM93JxsEaMuC59euuFRQ","key":"account_pubkey"}]}]
</details>

`example15.test` is mentioned 5 times there. Also, it doesn't show other names that I have registered. (https://github.com/aeternity/aepp-middleware/issues/83)

**Comment by johnsnewby** [comment]
Can you give examples of missing names please?

**Comment by davidyuk** [comment]
Here they are:
https://sdk-testnet.aepps.com/v2/names/example.test
https://sdk-testnet.aepps.com/v2/names/example2.test
https://sdk-testnet.aepps.com/v2/names/example6.test

**Comment by johnsnewby** [comment]
Dupes removed, with this amazing query:

```
delete from names n1 using (select min(ctid) as ctid, name, created_at_height from names group by name, created_at_height having count(1) > 1 ) n2 where n1.name=n2.name and n1.created_at_height = n2.created_at_height and n1.ctid <> n2.ctid;
```
The issue was a missing cascade, which I will add.

Missing names I shall investigate now.

**Comment by jsnewby** [comment]
I have deleted and recreated the names records, and I believe this issue is gone. Here is that I did, if it can be useful:

Find all NameClaimTex as comma separated list
`testnet=> select string_agg(cast(block_height as varchar), ',') from transactions where tx::text like '%NameClaimTx%';`
Delete existing name records:
`testnet=> delete from names;`
and reload the names:
`newby@ubuntu:~/aeternity/aepp-middleware-testnet$ STATUS_MAX_BLOCK_AGE=1200 PID_FILE=aepp_middleware.pid LOG_DIR=logs WEBSOCKET_ADDRESS=0.0.0.0:3021 ROCKET_PORT=8001 RUST_LOG=aepp_middleware AESOPHIA_URL=http://localhost:3080 NODE_URL=http://localhost:4013 RUST_BACKTRACE=full /usr/local/mdw/bin/aepp-middleware -H17441,74945,88236,17440,17803,17928,33020,35339,39524,45841,46323,49653,49681,59537,59623,60094,60095,60097,69691,69697,69699,69701,70121,70122,73999,74000,74944,74932,74953,74957,74964,74968,74975,76888,76890,81383,81383,80113,81638,106482,99005,84970,84991,104514,103275,103276,103337,88232,106483,103521,103534,103539,103551,106486,103562,103573,106504,103636,103640,103641,106443,103683,103690,103734,107252,106477,105077,103842,103860,104000,104106,104898,10914,105070,106554,104326,105112,105110,104499,105074,105075,106480,106481,106556,107259,107925,109811,109811,107927,109834,107292,107419,107420,107296,107300,107907,107423,107423,110353,107717,107718,107911,107794,108029,108082,108373,110065,108622,109570,109574,109577,109577,103257,111315,111316,111158`
